version: '3'

services:
        db:
                image: mysql:8
                ports:
                        - '3306:3306'
                environment:
                        MYSQL_DATABASE: 'db'
                        MYSQL_USER: 'root'
                        MYSQL_PASSWORD: 'password'
                        MYSQL_ROOT_PASSWORD: 'password'
                volumes:
                        - dbdatavolume:/var/lib/mysql
        back:
                build: backend
                #command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - ./backend/publisher-env-backend/:/app
                ports:
                        - "8000:8000"
                depends_on:
                        - db

        front:
                build: frontend
                ports:
                        - "80:3000"
                volumes:
                        -  ./frontend/publisher-env-frontend/:/usr/src/app/
                        -  /usr/src/app/node_modules
volumes:
  dbdatavolume: