version: '3'

services:
        db:
                image: postgres
                volumes:
                        - dbdatavolume:/var/lib/postgresql/data
        back:
                build: backend
                #command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - ./backend/publisher-env-backend/:/app
                ports:
                        - "8000:8000"
                depends_on:
                        - db

        front:
                build: frontend
                ports:
                        - "80:3000"
                volumes:
                        -  ./frontend/publisher-env-frontend/:/usr/src/app/
                        -  /usr/src/app/node_modules
volumes:
  dbdatavolume: